### ISSUE TITLE
关于depth_clustering里面通信机制的问题

### ISSUE THREAD

**Issue by lisilin013** [ZhanjiangSquad/depth_clustering_learning#1]
@EpsAvlc 
这个通信机制感觉大概类似于观察者模式，在main.cpp中我写了两个测试类，去测试，发现打印出来的id有些奇怪。

Publisher类的id两个函数结果一样，Subscriber类的id的两个函数结果就不一样，你帮我看看咋回事？百思不得其解。。。

**Comment by EpsAvlc** [comment]
列表初始化AbstractClient{}会使得UniqueID自增两次，原因不明。
